const CartAction = {

    ADD_TO_CART: "ADD_TO_CART",
    ADDING_TO_CART: "ADDING_TO_CART",
    ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
    ADD_TO_CART_FAILURE: "ADD_TO_CART_FAILURE",
    
    DELETE_PRODUCT_TO_CART: "DELETE_PRODUCT_TO_CART",
    DELETING_PRODUCT_TO_CART: "DELETING_PRODUCT_TO_CART",
    DELETE_PRODUCT_TO_CART_SUCCESS: "DELETE_PRODUCT_TO_CART_SUCCESS",
    DELETE_PRODUCT_TO_CART_FAILURE: "DELETE_PRODUCT_TO_CART_FAILURE",

    UPDATE_CART: 'UPDATE_CART'

};

export default CartAction;
