const FilmAction = {
    GET_ALL_FILM: 'GET_ALL_FILM',
    GETTING_ALL_FILM: 'GETTING_ALL_FILM',
    GET_ALL_FILM_SUCCESS: 'GET_ALL_FILM_SUCCESS',
    GET_ALL_FILM_FAILSE: 'GET_ALL_FILM_FAILSE',

    GET_DETAIL_FILM: 'GET_DETAIL_FILM',
    GETTING_DETAIL_FILM: 'GETTING_DETAIL_FILM',
    GET_DETAIL_FILM_SUCCESS: 'GET_DETAIL_FILM_SUCCESS',
    GET_DETAIL_FILM_FAILSE: 'GET_DETAIL_FILM_FAILSE',

    GET_DETAIL_SHOWTIME: 'GET_DETAIL_SHOWTIME',
    GETTING_DETAIL_SHOWTIME: 'GETTING_DETAIL_SHOWTIME',
    GET_DETAIL_SHOWTIME_SUCCESS: 'GET_DETAIL_SHOWTIME_SUCCESS',
    GET_DETAIL_SHOWTIME_FAILSE: 'GET_DETAIL_SHOWTIME_FAILSE',

    GET_SHOWTIME_BY_BRANCH: 'GET_SHOWTIME_BY_BRANCH',
    GETTING_SHOWTIME_BY_BRANCH: 'GETTING_SHOWTIME_BY_BRANCH',
    GET_SHOWTIME_BY_BRANCH_SUCCESS: 'GET_SHOWTIME_BY_BRANCH_SUCCESS',
    GET_SHOWTIME_BY_BRANCH_FAILSE: 'GET_SHOWTIME_BY_BRANCH_FAILSE',

};

export default FilmAction;