const CategoryAction = {
    GET_LIST_CATEGORY: 'GET_LIST_CATEGORY',
    GETTING_LIST_CATEGORY: 'GETING_LIST_CATEGORY',
    GET_LIST_CATEGORY_SUCCESS: 'GETING_LIST_CATEGORY_SUCCESS',
    GET_LIST_CATEGORY_FAILURE: 'GETING_LIST_CATEGORY_FAILURE',

    GET_LIST_TREE_CATEGORY: 'GET_LIST_TREE_CATEGORY',
    GETITNG_LIST_TREE_CATEGORY: 'GETITNG_LIST_TREE_CATEGORY',
    GET_LIST_TREE_CATEGORY_SUCCESS: 'GET_LIST_TREE_CATEGORY_SUCCESS',
    GET_LIST_TREE_CATEGORY_FAILURE: 'GET_LIST_TREE_CATEGORY_FAILURE',
};

export default CategoryAction;
