const LoginAction = {
    SUBMIT_LOGIN: 'SUBMIT_LOGIN',
    SUBMITING_LOGIN: 'SUBMITING_LOGIN',
    SUBMIT_LOGIN_SUCCESS: 'SUBMIT_LOGIN_SUCCESS',
    SUBMIT_LOGIN_FAILURE: 'SUBMIT_LOGIN_FAILURE',

    SUBMIT_REGISTER: 'SUBMIT_REGISTER',
    SUBMITING_REGISTER: 'SUBMITING_REGISTER',
    SUBMIT_REGISTER_SUCCESS: 'SUBMITING_REGISTER_SUCCESS',
    SUBMIT_REGISTER_FAILURE: 'SUBMITING_REGISTER_FAILURE',

    GET_USER_DETAIL: 'GET_USER_DETAIL',
    GETING_USER_DETAIL: 'GETING_USER_DETAIL',
    GET_USER_DETAIL_SUCCESS: 'GET_USER_DETAIL_SUCCESS',
    GET_USER_DETAIL_FAILUSE: 'GET_USER_DETAIL_FAILURE',

    CHANGE_PROFILE: 'CHANGE_PROFILE',
    CHANGING_PROFILE: 'CHANGING_PROFILE',
    CHANGE_PROFILE_SUCCESS: 'CHANGE_PROFILE_SUCCESS',
    CHANGE_PROFILE_FAILUSE: 'CHANGE_PROFILE_FAILUSE',

    CHANGE_PASSWORD: 'CHANGE_PASSWORD',

    ISADMIN: 'ISADMIN',
};

export default LoginAction;
