const OrderAction = {
    GET_LIST_ORDER_BY_USERID: 'GET_LIST_ORDER_BY_USERID',
    GETTING_LIST_ORDER_BY_USERID: 'GETTING_LIST_ORDER_BY_USERID',
    GET_LIST_ORDER_BY_USERID_SUCCESS: 'GET_LIST_ORDER_BY_USERID_SUCCESS',
    GET_LIST_ORDER_BY_USERID_FAILURE: 'GET_LIST_ORDER_BY_USERID_FAILURE',

    GET_LIST_ORDER_BY_STATUS: 'GET_LIST_ORDER_BY_STATUS',


    GET_ORDER_BY_ID: 'GET_ORDER_BY_ID',
    GETTING_ORDER_BY_ID: 'GETTING_ORDER_BY_ID',
    GET_ORDER_BY_ID_SUCCESS: 'GET_ORDER_BY_ID_SUCCESS',
    GET_ORDER_BY_ID_FAILURE: 'GET_ORDER_BY_ID_FAILURE',

    ADD_ORDER: 'ADD_ORDER',
    ADDING_ORDER: 'ADDTING_ORDER',
    ADD_ORDER_SUCCESS: 'ADD_ORDER_SUCCESS',
    ADD_ORDER_FAILURE: 'ADD_ORDER_FAILURE',

    GET_FOOD: 'GET_FOOD',
    GETTING_FOOD: 'GETTING_FOOD',
    GET_FOOD_SUCCESS: 'GET_FOOD_SUCCESS',
    GET_FOOD_FAILURE: 'GET_FOOD_FAILURE',

    GET_SHOWTIME: 'GET_SHOWTIME',
    GETTING_SHOWTIME: 'GETTING_SHOWTIME',
    GET_SHOWTIME_SUCCESS: 'GET_SHOWTIME_SUCCESS',
    GET_SHOWTIME_FAILURE: 'GET_SHOWTIME_FAILURE',

    GET_LINK_PAYMENT: 'GET_LINK_PAYMENT',
    GETTING_LINK_PAYMENT: 'GETTING_LINK_PAYMENT',
    GET_LINK_PAYMENT_SUCCESS: 'GET_LINK_PAYMENT_SUCCESS',
    GET_LINK_PAYMENT_FAILURE: 'GET_LINK_PAYMENT_FAILURE',

    UPDATE_STATUS_PAYMENT: 'UPDATE_STATUS_PAYMENT',
    GET_DETAIL_BY_ID: 'GET_DETAIL_BY_ID',
    GET_DETAIL_BY_ID_SUCCESS: 'GET_DETAIL_BY_ID_SUCCESS',

    CHANGE_STATUS_ORDER: 'CHANGE_STATUS_ORDER'
};

export default OrderAction;
