const ProductAction = {
    GET_LIST_PRODUCT: 'GET_LIST_PRODUCT',
    GETTING_LIST_PRODUCT: 'GETING_LIST_PRODUCT',
    GET_LIST_PRODUCT_SUCCESS: 'GETING_LIST_PRODUCT_SUCCESS',
    GET_LIST_PRODUCT_FAILURE: 'GETING_LIST_PRODUCT_FAILURE',

    GET_LIST_PRODUCT_BY_CATEGORY: 'GET_LIST_PRODUCT_BY_CATEGORY',
    GETTITNG_LIST_PRODUCT_BY_CATEGORY: 'GETTITNG_LIST_PRODUCT_BY_CATEGORY',
    GET_LIST_PRODUCT_BY_CATEGORY_SUCCESS: 'GET_LIST_PRODUCT_BY_CATEGORY_SUCCESS',
    GET_LIST_PRODUCT_BY_CATEGORY_FAILURE: 'GET_LIST_PRODUCT_BY_CATEGORY_FAILURE',

    GET_PRODUCT_BY_ID: 'GET_PRODUCT_BY_ID',
    GETING_PRODUCT_BY_ID: 'GETING_PRODUCT_BY_ID',
    GET_PRODUCT_BY_ID_SUCCESS: 'GET_PRODUCT_BY_ID_SUCCESS',
    GET_PRODUCT_BY_ID_FAILURE: 'GET_PRODUCT_BY_ID_FAILURE',
    GET_BEST_SELLER:'GET_BEST_SELLER',

    ADD_PRODUCT: 'ADD_PRODUCT',
    ADDING_PRODUCT: 'ADDING_PRODUCT',
    ADD_PRODUCT_SUCCESS: 'ADD_PRODUCT_SUCCESS',
    ADD_PRODUCT_FAILURE: 'ADD_PRODUCT_FAILURE',

    DELETE_PRODUCT: 'DELETE_PRODUCT',
    DELETING_PRODUCT: 'DELETING_PRODUCT',
    DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_FAILURE: 'DELETE_PRODUCT_FAILURE',
};

export default ProductAction;
