const AppAction = {
    GET_SETTINGS: 'GET_SETTINGS',
    GET_SETTINGS_SUCCESS: 'GET_SETTINGS_SUCCESS',
    GET_SETTINGS_FAILURE: 'GET_SETTINGS_FAILURE',

    GET_DECENTRALIZATION: 'GET_DECENTRALIZATION',
    GET_DECENTRALIZATION_SUCCESS: 'GET_DECENTRALIZATION_SUCCESS',
    GET_DECENTRALIZATION_FAILURE: 'GET_DECENTRALIZATION_FAILURE',
};

export default AppAction;