const AddressAction = {
    GET_PROVINCE: 'GET_PROVINCE',
    GETING_PROVINCE: 'GETING_PROVINCE',
    GET_PROVINCE_SUCCESS: 'GET_PROVINCE_SUCCESS',
    GET_PROVINCE_FAILURE: 'GET_PROVINCE_FAILURE',

    GET_DISTRICT: 'GET_DISTRICT',
    GETING_DISTRICT: 'GETING_DISTRICT',
    GET_DISTRICT_SUCCESS: 'SUBMITING_REGISTER_SUCCESS',
    GET_DISTRICT_FAILURE: 'GET_DISTRICT_FAILURE',

    GET_COMMUNITY: 'GET_COMMUNITY',
    GETING_COMMUNITY: 'GETING_COMMUNITY',
    GET_COMMUNITY_SUCCESS: 'GET_COMMUNITY_SUCCESS',
    GET_COMMUNITY_FAILUSE: 'GET_COMMUNITY_FAILUSE',

    GET_LIST_ADDRESS_BY_USER: 'GET_LIST_ADDRESS_BY_USER',
    GETING_LIST_ADDRESS_BY_USER: 'GETING_LIST_ADDRESS_BY_USER',
    GET_LIST_ADDRESS_BY_USER_SUCCESS: 'GET_LIST_ADDRESS_BY_USER_SUCCESS',
    GET_LIST_ADDRESS_BY_USER_FAILUSE: 'GET_LIST_ADDRESS_BY_USER_FAILUSE',

    ADD_ADDRESS: 'ADD_ADDRESS',
    ADDING_ADDRESS: 'ADDING_ADDRESS',
    ADD_ADDRESS_SUCCESS: 'ADD_ADDRESS_SUCCESS',
    ADD_ADDRESS_FAILUSE: 'ADD_ADDRESS_FAILUSE',

    GET_BRANCH: 'GET_BRANCH',

    GET_POSITION: 'GET_POSITION',

    GET_MESSAGE: 'GET_MESSAGE',
};

export default AddressAction;
